# Refresh vendored modules and configs into vendor/
# Run before `docker build` to update vendored copies.
#
# Default: download tarballs from GitHub (no git clone, no auth needed)
# --local: use local ~/repos/ directories (original rsync behavior)

const cozy_root = (path self | path dirname | path dirname)
const vendor_yml = (path self | path dirname | path join vendor.yml)
# Generated repo→URL manifest for in-sandbox `cozy sync-repos`. It can't read
# this host-only vendor.yml, so we project the list into the shipped cozy-module/.
const sync_manifest = ($cozy_root | path join cozy-module vendored-repos.nuon)

def load-modules []: nothing -> list<record<repo: string, github: string, modules: list<string>>> {
    open $vendor_yml
}

# Regenerate vendored-repos.nuon from vendor.yml. cozy is appended (it isn't
# self-vendored, but `cozy sync-repos` still pulls it). Deterministic order so
# the committed file diffs cleanly.
def write-sync-manifest [] {
    let header = "# GENERATED by `nu toolkit/vendor.nu` from toolkit/vendor.yml — do not edit by hand.
# repo → clone URL for in-sandbox `cozy sync-repos`, which cannot read the
# host-only toolkit/vendor.yml. cozy itself is appended (it is not self-vendored).
"
    let rows = load-modules
        | select repo github
        | each {|it| {name: $it.repo, url: $"https://github.com/($it.github).git"} }
        | append {name: cozy, url: "https://github.com/nushell-prophet/cozy.git"}
        | sort-by name
    $header + ($rows | to nuon --indent 2) + "\n" | save -f $sync_manifest
    print $"  (ansi green)Manifest:(ansi reset) cozy-module/vendored-repos.nuon \(($rows | length) repos)"
}

def "nu-complete vendor repos" []: nothing -> list<string> {
    open $vendor_yml | get repo
}

# Curl args for the GitHub API: fail-fast on HTTP errors (so a JSON rate-
# limit body never reaches `tar xz` as "not in gzip format"), show errors
# even with -s, follow redirects. Bearer auth when GH_TOKEN/GITHUB_TOKEN
# is set bumps the anonymous 60 req/hr limit to 5000.
def gh-curl-args []: nothing -> list<string> {
    let token = $env.GH_TOKEN? | default ($env.GITHUB_TOKEN? | default '')
    if ($token | is-empty) { [] } else { ['-H' $"Authorization: bearer ($token)"] }
}

def fetch-tarball [github: string]: nothing -> path {
    let tmp = mktemp -d
    let url = $"https://api.github.com/repos/($github)/tarball"
    print $"  (ansi cyan)Downloading:(ansi reset) ($github)"
    curl -fsSL ...(gh-curl-args) $url | tar xz -C $tmp --strip-components=1
    $tmp
}

def copy-module [src: path dst: path] {
    if not ($src | path exists) {
        print $"  (ansi red)Missing:(ansi reset) ($src)"
        return
    }
    if ($src | path type) == 'file' {
        mkdir ($dst | path dirname)
        cp $src $dst
    } else {
        mkdir $dst
        ^rsync -a --prune-empty-dirs --exclude='.git' --exclude='.DS_Store' --exclude='lazytests' $"($src)/" $"($dst)/"
    }
}

const ignore_repos = [
    ".github"
    config-tools
    cozy
    cozy-docker-sandbox-toolkit
    my-dot-claude
    my-dotfiles
    npshow-module
    nushell-history-based-completions
    nushell-prophet-journal
    nushell-prophet-manuals
    nushell-show
]

# Check for nushell-prophet repos not yet in vendor.yml
export def "main check" [--add (-a)] {
    let known = load-modules
        | where github starts-with 'nushell-prophet/'
        | get github
        | each { $in | split row '/' | last }

    let remote = curl -fsSL ...(gh-curl-args) "https://api.github.com/users/nushell-prophet/repos?per_page=100"
        | from json
        | get name

    let new = $remote
        | where {|r| $r not-in $known and $r not-in $ignore_repos }

    if ($new | is-empty) {
        print "No new nushell-prophet repos found."
        return
    }

    print $"New repos not in vendor.yml:"
    $new | each { print $"  ($in)" }

    if $add {
        let entries = $new | each {|name|
                {repo: $name github: $"nushell-prophet/($name)" modules: [$name]}
            }
        let current = load-modules
        $current | append $entries | to yaml | save -f $vendor_yml
        print $"\nAdded ($new | length) repo\(s\) to vendor.yml with default modules."
    } else {
        print $"\nUse --add to append them to vendor.yml with default modules."
    }
}

# Commit the freshly vendored files with a standard message. Pathspec-scoped
# to the touched vendor/ dir(s) so unrelated staged changes stay out of the
# commit, and a no-op (no diff) just prints instead of failing.
def commit-vendor [groups: list<any> repo: string] {
    let paths = if $repo == null {
        [($cozy_root | path join vendor)]
    } else {
        $groups | each {|g| $cozy_root | path join vendor $g.repo }
    }
    # The generated manifest tracks the repo set, so commit it alongside.
    let paths = $paths | append $sync_manifest

    cd $cozy_root
    ^git add ...$paths
    let staged = ^git diff --cached --quiet -- ...$paths | complete | get exit_code
    if $staged == 0 {
        print $"  (ansi yellow)Nothing to commit(ansi reset)"
        return
    }

    let subject = if $repo == null { 'vendor: refresh all modules' } else { $'vendor: update ($repo)' }
    ^git commit -m $subject -- ...$paths
    print $"  (ansi green)Committed:(ansi reset) ($subject)"
}

export def main [
    repo?: string@"nu-complete vendor repos" # vendor only this repo from vendor.yml; omit to refresh all
    --local (-l)
    --no-commit # skip the automatic git commit of the vendored changes
] {
    # Why: derive vendor_dir from the script's own location (path self)
    # so this script works regardless of caller's pwd. The script lives
    # at <cozy_root>/toolkit/vendor.nu.
    let vendor_dir = $cozy_root | path join vendor

    let all_groups = load-modules
    let groups = if $repo == null { $all_groups } else { $all_groups | where repo == $repo }
    if ($groups | is-empty) {
        error make {msg: $"repo '($repo)' not found in vendor.yml"}
    }

    # Wipe scope: the whole vendor/ when refreshing everything, else just the
    # target repo's dir so the other vendored modules are left untouched.
    if $repo == null {
        rm -rf $vendor_dir
        mkdir $vendor_dir
    } else {
        for $group in $groups { rm -rf ($vendor_dir | path join $group.repo) }
    }

    if $local {
        let git_dir = $cozy_root | path dirname
        for $group in $groups {
            for module in $group.modules {
                let src = $git_dir | path join $group.repo $module
                let dst = $vendor_dir | path join $group.repo $module
                copy-module $src $dst
                print $"  (ansi green)Copied:(ansi reset) ($group.repo)/($module)"
            }
        }
    } else {
        for $group in $groups {
            let tmp = fetch-tarball $group.github
            for module in $group.modules {
                let src = $tmp | path join $module
                let dst = $vendor_dir | path join $group.repo $module
                copy-module $src $dst
                print $"  (ansi green)Vendored:(ansi reset) ($group.repo)/($module)"
            }
            rm -rf $tmp
        }
    }

    # Always regenerate the manifest — it's derived from vendor.yml, so a
    # single-repo run can still need it refreshed (e.g. after a vendor.yml edit).
    write-sync-manifest

    if not $no_commit {
        commit-vendor $groups $repo
    }
}
